checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-bionic
  environment:
    php: 8.1.12
    variables:
      XDEBUG_MODE: 'coverage'
  nodes:
    coverage:
      services:
        mariadb: 10.6.12
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml  # Or "./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml"
            coverage:
              file: 'build/coverage/clover.xml'
              format: 'php-clover'
    analysis:
      tests:
        override:
        - php-scrutinizer-run