checks:
  php:
    code_rating: true
    duplication: true

build:
  image: default-bionic
  environment:
    php: 8.1.12
  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
        - ./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml  # Or "./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml"
        idle_timeout: 1200
        coverage:
          file: 'build/coverage/clover.xml'
          format: 'php-clover'