<?php
/**
 * This file is part of the Divergence package.
 *
 * (c) Henry Paradiz <henry.paradiz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Divergence\IO\Database\Writer;

use Exception;

class PostgreSQL extends MySQL
{
    protected const DIRECT_SQL_TYPES = [
        'boolean' => 'boolean',
        'smallint' => 'smallint',
        'mediumint' => 'integer',
        'int' => 'integer',
        'integer' => 'integer',
        'uint' => 'integer',
        'year' => 'integer',
        'bigint' => 'bigint',
        'float' => 'real',
        'double' => 'double precision',
        'clob' => 'text',
        'serialized' => 'text',
        'json' => 'text',
        'enum' => 'text',
        'set' => 'text',
        'blob' => 'bytea',
        'binary' => 'bytea',
        'timestamp' => 'timestamp',
        'datetime' => 'timestamp',
        'time' => 'time',
        'date' => 'date',
    ];

    public static function compileFields($recordClass, $historyVariant = false)
    {
        $queryString = [];

        static::eachNonRevisionField($recordClass, function ($fieldId) use (&$queryString, $recordClass, $historyVariant) {
            $queryString[] = static::getFieldDefinition($recordClass, $fieldId, $historyVariant);
        });

        return $queryString;
    }

    public static function getContextIndex($recordClass)
    {
        return 'CREATE INDEX IF NOT EXISTS "' . $recordClass::$tableName . '_context" ON "' . $recordClass::$tableName . '" ("' . $recordClass::getColumnName('ContextClass') . '","' . $recordClass::getColumnName('ContextID') . '")';
    }

    public static function getCreateTable($recordClass, $historyVariant = false)
    {
        $indexes = static::getStandardIndexes($recordClass, $historyVariant);
        $queryString = static::getPostgreSqlBaseStatements($recordClass, $historyVariant);
        $postCreateStatements = [];

        if (!$historyVariant) {
            static::appendContextIndex($postCreateStatements, $recordClass);
        }

        static::appendPostgreSqlIndexes($postCreateStatements, $recordClass, $indexes);

        $createSQL = sprintf(
            "CREATE TABLE IF NOT EXISTS \"%s\" (\n\t%s\n);",
            static::getTargetTableName($recordClass, $historyVariant),
            join("\n\t,", $queryString)
        );

        if (!empty($postCreateStatements)) {
            $createSQL .= PHP_EOL . PHP_EOL . join(";" . PHP_EOL, $postCreateStatements) . ';';
        }

        return $createSQL;
    }

    protected static function getPostgreSqlBaseStatements(string $recordClass, bool $historyVariant): array
    {
        $queryString = [];

        if ($historyVariant) {
            $queryString[] = '"RevisionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        }

        return array_merge($queryString, static::compileFields($recordClass, $historyVariant));
    }

    protected static function appendPostgreSqlIndexes(array &$postCreateStatements, string $recordClass, array $indexes): void
    {
        foreach ($indexes as $indexName => $index) {
            if (!empty($index['fulltext'])) {
                continue;
            }

            $postCreateStatements[] = sprintf(
                'CREATE %sINDEX IF NOT EXISTS "%s" ON "%s" ("%s")',
                !empty($index['unique']) ? 'UNIQUE ' : '',
                $indexName,
                $recordClass::$tableName,
                join('","', $index['fields'])
            );
        }
    }

    public static function getSQLType($field)
    {
        if (isset(static::DIRECT_SQL_TYPES[$field['type']])) {
            return static::DIRECT_SQL_TYPES[$field['type']];
        }

        if ($field['type'] === 'tinyint') {
            return 'smallint';
        }

        if ($field['type'] === 'decimal') {
            return sprintf('numeric(%s,%s)', $field['precision'], $field['scale']);
        }

        if (in_array($field['type'], ['password', 'string', 'varchar', 'list'], true)) {
            return static::getVariableCharacterType($field);
        }

        throw new Exception("getSQLType: unhandled type $field[type]");
    }

    public static function getFieldDefinition($recordClass, $fieldName, $historyVariant = false)
    {
        $field = static::normalizeFieldOptions($recordClass, $fieldName);

        if (!empty($field['primary']) && !empty($field['autoincrement']) && !$historyVariant) {
            return '"' . $field['columnName'] . '" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        }

        $fieldDef = static::buildPostgreSqlFieldPrefix($field, $historyVariant);
        $fieldDef .= ' ' . ($field['notnull'] ? 'NOT NULL' : 'NULL');
        $fieldDef = static::appendPostgreSqlFieldDefault($fieldDef, $field);

        if (!empty($field['unique']) && !$historyVariant) {
            $fieldDef .= ' UNIQUE';
        }

        return $fieldDef;
    }

    protected static function buildPostgreSqlFieldPrefix(array $field, bool $historyVariant): string
    {
        $fieldDef = '"' . $field['columnName'] . '" ' . static::getSQLType($field);

        if (!empty($field['primary']) && !$historyVariant) {
            $fieldDef .= ' PRIMARY KEY';
        }

        return $fieldDef;
    }

    protected static function appendPostgreSqlFieldDefault(string $fieldDef, array $field): string
    {
        if (($field['type'] == 'timestamp') && ($field['default'] == 'CURRENT_TIMESTAMP')) {
            return $fieldDef . ' DEFAULT CURRENT_TIMESTAMP';
        }

        if (empty($field['notnull']) && ($field['default'] == null)) {
            return $fieldDef . ' DEFAULT NULL';
        }

        if (!isset($field['default'])) {
            return $fieldDef;
        }

        if ($field['type'] == 'boolean') {
            return $fieldDef . ' DEFAULT ' . ($field['default'] ? 'TRUE' : 'FALSE');
        }

        if (in_array($field['type'], ['int', 'integer', 'uint', 'tinyint', 'smallint', 'mediumint', 'bigint', 'float', 'double', 'decimal'], true)) {
            return $fieldDef . ' DEFAULT ' . $field['default'];
        }

        return $fieldDef . " DEFAULT '" . str_replace("'", "''", (string) $field['default']) . "'";
    }
}
