<?php
/**
 * This file is part of the Divergence package.
 *
 * (c) Henry Paradiz <henry.paradiz@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Divergence\IO\Database\Writer;

use Exception;

class PostgreSQL extends MySQL
{
    public static function compileFields($recordClass, $historyVariant = false)
    {
        $queryString = [];
        $fields = static::getAggregateFieldOptions($recordClass);

        foreach ($fields as $fieldId => $field) {
            if ($field['columnName'] == 'RevisionID') {
                continue;
            }

            $queryString[] = static::getFieldDefinition($recordClass, $fieldId, $historyVariant);
        }

        return $queryString;
    }

    public static function getContextIndex($recordClass)
    {
        return 'CREATE INDEX IF NOT EXISTS "' . $recordClass::$tableName . '_context" ON "' . $recordClass::$tableName . '" ("' . $recordClass::getColumnName('ContextClass') . '","' . $recordClass::getColumnName('ContextID') . '")';
    }

    public static function getCreateTable($recordClass, $historyVariant = false)
    {
        $indexes = $historyVariant ? [] : $recordClass::$indexes;
        $queryString = [];
        $postCreateStatements = [];

        if ($historyVariant) {
            $queryString[] = '"RevisionID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        }

        $queryString = array_merge($queryString, static::compileFields($recordClass, $historyVariant));

        if (!$historyVariant && $recordClass::fieldExists('ContextClass') && $recordClass::fieldExists('ContextID')) {
            $postCreateStatements[] = static::getContextIndex($recordClass);
        }

        foreach ($indexes as $indexName => $index) {
            foreach ($index['fields'] as &$indexField) {
                $indexField = $recordClass::getColumnName($indexField);
            }

            if (!empty($index['fulltext'])) {
                continue;
            }

            $postCreateStatements[] = sprintf(
                'CREATE %sINDEX IF NOT EXISTS "%s" ON "%s" ("%s")',
                !empty($index['unique']) ? 'UNIQUE ' : '',
                $indexName,
                $recordClass::$tableName,
                join('","', $index['fields'])
            );
        }

        $createSQL = sprintf(
            "CREATE TABLE IF NOT EXISTS \"%s\" (\n\t%s\n);",
            $historyVariant ? $recordClass::getHistoryTable() : $recordClass::$tableName,
            join("\n\t,", $queryString)
        );

        if (!empty($postCreateStatements)) {
            $createSQL .= PHP_EOL . PHP_EOL . join(";" . PHP_EOL, $postCreateStatements) . ';';
        }

        return $createSQL;
    }

    public static function getSQLType($field)
    {
        switch ($field['type']) {
            case 'boolean':
                return 'boolean';
            case 'tinyint':
            case 'smallint':
                return 'smallint';
            case 'mediumint':
            case 'int':
            case 'integer':
            case 'uint':
            case 'year':
                return 'integer';
            case 'bigint':
                return 'bigint';
            case 'decimal':
                return sprintf('numeric(%s,%s)', $field['precision'], $field['scale']);
            case 'float':
                return 'real';
            case 'double':
                return 'double precision';

            case 'password':
            case 'string':
            case 'varchar':
            case 'list':
                return sprintf(!$field['length'] || $field['type'] == 'varchar' ? 'varchar(%u)' : 'char(%u)', $field['length'] ? $field['length'] : 255);
            case 'clob':
            case 'serialized':
            case 'json':
            case 'enum':
            case 'set':
                return 'text';
            case 'blob':
            case 'binary':
                return 'bytea';

            case 'timestamp':
            case 'datetime':
                return 'timestamp';
            case 'time':
                return 'time';
            case 'date':
                return 'date';

            default:
                throw new Exception("getSQLType: unhandled type $field[type]");
        }
    }

    public static function getFieldDefinition($recordClass, $fieldName, $historyVariant = false)
    {
        $field = static::getAggregateFieldOptions($recordClass, $fieldName);
        $rootClass = $recordClass::getRootClassName();

        if ($rootClass && !$rootClass::fieldExists($fieldName)) {
            $field['notnull'] = false;
        }

        if ($field['columnName'] == 'Class' && $field['type'] == 'enum' && !in_array($rootClass, $field['values']) && !count($rootClass::getStaticSubClasses())) {
            array_unshift($field['values'], $rootClass);
        }

        if (!empty($field['primary']) && !empty($field['autoincrement']) && !$historyVariant) {
            return '"' . $field['columnName'] . '" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
        }

        $fieldDef = '"' . $field['columnName'] . '" ' . static::getSQLType($field);

        if (!empty($field['primary']) && !$historyVariant) {
            $fieldDef .= ' PRIMARY KEY';
        }

        $fieldDef .= ' ' . ($field['notnull'] ? 'NOT NULL' : 'NULL');

        if (($field['type'] == 'timestamp') && ($field['default'] == 'CURRENT_TIMESTAMP')) {
            $fieldDef .= ' DEFAULT CURRENT_TIMESTAMP';
        } elseif (empty($field['notnull']) && ($field['default'] == null)) {
            $fieldDef .= ' DEFAULT NULL';
        } elseif (isset($field['default'])) {
            if ($field['type'] == 'boolean') {
                $fieldDef .= ' DEFAULT ' . ($field['default'] ? 'TRUE' : 'FALSE');
            } elseif (in_array($field['type'], ['int', 'integer', 'uint', 'tinyint', 'smallint', 'mediumint', 'bigint', 'float', 'double', 'decimal'], true)) {
                $fieldDef .= ' DEFAULT ' . $field['default'];
            } else {
                $fieldDef .= " DEFAULT '" . str_replace("'", "''", (string) $field['default']) . "'";
            }
        }

        if (!empty($field['unique']) && !$historyVariant) {
            $fieldDef .= ' UNIQUE';
        }

        return $fieldDef;
    }
}
